// <auto-generated />
using MicraPro.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicraPro.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(SharedDbContext))]
    [Migration("20251110122628_KeyValueStore")]
    partial class KeyValueStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("MicraPro.Shared.Infrastructure.ConfigurationEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("MicraPro.Shared.Infrastructure.KeyValueStore.KeyValueEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("KeyValueStore");
                });
#pragma warning restore 612, 618
        }
    }
}
